### ISSUE TITLE
What GitHub/Gitlab Issues has the 2024 Joint OGC ASF OSGeo Code Sprint created in other repositories?

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/developer-events#130]
Please let us know what GitHub/Gitlab Issues you have created during the code sprint.

**Comment by ghobona** [comment]
https://github.com/opengeospatial/NamingAuthority/issues/278

**Comment by ghobona** [comment]
https://github.com/opengeospatial/teamengine/issues/618

**Comment by ghobona** [comment]
https://github.com/geopython/pygeoapi/issues/1563

**Comment by ghobona** [comment]
https://github.com/geopython/pygeoapi/issues/1562

**Comment by ghobona** [comment]
https://github.com/geopython/pygeoapi/issues/1559

**Comment by ghobona** [comment]
https://github.com/geopython/pygeoapi/issues/1557

**Comment by ghobona** [comment]
https://github.com/geopython/pygeoapi/issues/1551

**Comment by ghobona** [comment]
https://github.com/opengeospatial/ets-geotiff11/issues/43

**Comment by joostfarla** [comment]
https://github.com/opengeospatial/ogc-feat-geo-json/issues/120
https://github.com/opengeospatial/ogc-feat-geo-json/issues/121
https://github.com/opengeospatial/ogc-feat-geo-json/issues/122
https://github.com/opengeospatial/ogc-feat-geo-json/issues/123
https://github.com/opengeospatial/ogc-feat-geo-json/issues/124

**Comment by ghobona** [comment]
https://github.com/opengeospatial/ogcapi-records/pull/346

**Comment by ghobona** [comment]
https://github.com/opengeospatial/ogcapi-records/pull/345

**Comment by dstenger** [comment]
https://github.com/opengeospatial/cite/issues/66
https://github.com/opengeospatial/ets-ogcapi-features10/issues/235
https://github.com/opengeospatial/ets-geotiff11/issues/43
https://github.com/opengeospatial/ets-cat30/issues/55

**Comment by ghobona** [comment]
https://github.com/opengeospatial/ogcapi-features/pull/897

**Comment by ghobona** [comment]
https://github.com/opengeospatial/ogcapi-features/pull/896

**Comment by ghobona** [comment]
https://github.com/opengeospatial/ogcapi-features/pull/895

**Comment by ghobona** [comment]
https://github.com/opengeospatial/ogcapi-features/pull/894

**Comment by ghobona** [comment]
https://github.com/opengeospatial/ogcapi-features/pull/892

**Comment by ghobona** [comment]
https://github.com/opengeospatial/ogcapi-features/pull/891

**Comment by ghobona** [comment]
https://github.com/opengeospatial/ogcapi-features/pull/890

**Comment by TaehoonK** [comment]
https://github.com/opengeospatial/ogcapi-movingfeatures/issues/61
https://github.com/aistairc/mf-api/issues/10

**Comment by cportele** [comment]
https://github.com/opengeospatial/ogcapi-features/pull/888

In addition, the following existing PRs were reviewed, updated and merged:

https://github.com/opengeospatial/ogcapi-features/pull/886
https://github.com/opengeospatial/ogcapi-features/pull/884
https://github.com/opengeospatial/ogcapi-features/pull/883
https://github.com/opengeospatial/ogcapi-features/pull/881

And the following PR was reviewed and updated, but not yet merged:

https://github.com/opengeospatial/ogc-feat-geo-json/pull/116

**Comment by doublebyte1** [comment]
https://github.com/geopython/pygeoapi/issues/1545
https://github.com/geopython/pygeoapi/pull/1554

https://github.com/geopython/pygeoapi/issues/1546

https://github.com/geopython/pygeoapi/issues/1559
https://github.com/geopython/pygeoapi/pull/1566

https://github.com/geopython/pygeoapi/issues/1551

https://github.com/geopython/pygeoapi/pull/1571
