### ISSUE TITLE
What GitHub Issues has the September 2022 Joint OGC ISO Metadata Code Sprint created in other OGC, STAC and ISO repositories?

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/developer-events#18]
Please post links to GitHub issues you create during the code sprint.

**Comment by ghobona** [comment]
Repo created for STAC Collection Search Extension. https://github.com/stac-api-extensions/collection-search

Thanks @m-mohr

**Comment by ghobona** [comment]
https://github.com/opengeospatial/ogcapi-records/issues/180

**Comment by ghobona** [comment]
https://github.com/opengeospatial/ogc-feat-geo-json/issues/68

**Comment by ghobona** [comment]
https://github.com/opengeospatial/ogc-feat-geo-json/issues/69

**Comment by ghobona** [comment]
https://github.com/opengeospatial/ogc-feat-geo-json/issues/70

**Comment by ghobona** [comment]
https://github.com/stac-api-extensions/collection-search/issues/2

**Comment by m-mohr** [comment]
https://github.com/opengeospatial/ogcapi-records/issues/178

**Comment by ghobona** [comment]
https://github.com/geopython/OWSLib/issues/836

**Comment by ghobona** [comment]
Discussed https://github.com/opengeospatial/ogcapi-records/issues/28

**Comment by IvanSanchez** [comment]
See also https://github.com/opengeospatial/ogc-feat-geo-json/issues/71

**Comment by IvanSanchez** [comment]
See also https://github.com/opengeospatial/ogc-feat-geo-json/issues/72

**Comment by ghobona** [comment]
Creating a separate comment for https://github.com/opengeospatial/ogc-feat-geo-json/issues/72

**Comment by ghobona** [comment]
Creating a separate comment for https://github.com/opengeospatial/ogc-feat-geo-json/issues/73
