### ISSUE TITLE
Ideas for Collaborative OGC OSGeo ASF projects at the 2022 code sprint

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/developer-events#2]
What activities or tasks might OSGeo and Apache projects work on together with OGC working groups during the 2022 joint code sprint?

Post your ideas as comments in this GitHub Issue.

**Comment by ghobona** [comment]
**Pipeline for getting feature collections out of QGIS, into GeoServer and then Apache Jena Fuseki**

This [idea](https://docs.ogc.org/per/21-008.html#_apache_jena_2) came up during the 2021 Joint OGC OSGeo ASF Code Sprint. 

During the 2021 joint code sprint, the Apache Jena team discussed an approach with the GeoServer team for enabling the export of a feature collection from QGIS to GeoServer, and then to Apache Jena Fuseki. Fuseki offers a SPARQL Server interface on top of Apache Jena. The groups concluded that it would be possible to create a plug-in for QGIS that allows it to post GeoJSON to GeoServer. An additional plug-in could then be implemented to export GeoJSON-LD from GeoServer to Fuseki.

The GeoJSON-LD document would be interpreted as RDF triples by Fuseki. There was also discussion about how to represent the schema of the feature collection. SHACL was identified as a possible candidate for representing the schema of the feature collection. Jena supports SHACL.

**Comment by desruisseaux** [comment]
# GIGS 2.0 implementation

A new version of Geospatial Integrity for Geoscience Software (GIGS) tests has been published. We propose to update the GeoAPI tests with this new revisions and "test the tests" on at least two projects: PROJ (using PROJ-JNI) and Apache SIS.

**Comment by desruisseaux** [comment]
# GGXF implementation

The [Gridded Geodetic data eXchange Format](https://github.com/opengeospatial/CRS-Gridded-Geodetic-data-eXchange-Format) (GGXF) format is close to ready for implementation experiment and a prototype is already available in Python. We propose to start implementation experiments in Apache SIS or other projects.

**Comment by desruisseaux** [comment]
# Experimental Python ⟷ Java bridge with Panama
GeoAPI has a [draft of Python API](http://www.geoapi.org/snapshot/python/index.html) (mostly for Coordinate Reference Systems at this time) and a [Java ⟷ Python bridge using JNI](http://www.geoapi.org/java-python/index.html). We propose to explore the use of project Panama (incubator) in replacement of JNI. The bridge would work for any GeoAPI implementation, but we can use Apache SIS for testing purposes.

**Comment by desruisseaux** [comment]
# Visual components for Apache SIS
Apache SIS has a small [JavaFX application](https://sis.apache.org/javafx.html) which can be used for testing some of its capabilities. It currently shows only a small fraction of what SIS can do. More components would be welcome, for example a form for creating customized Coordinate Reference System (CRS) definitions.
