### ISSUE TITLE
What is everybody going to be working on at the 2022 Joint OGC OSGeo ASF Code Sprint?

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/developer-events#4]
Post a comment letting us know what you are going to be working on.

**Comment by chris-little** [comment]
I probably will not be coding, but instead supplying use cases, examples, and guidance around the OGC API-EDR. Especially if developers think EDR is only about Environmental Data Retrieval - it is not - it really is a spatiotemporal data retrieval API.
I am particularly interested in ensuring the API-EDR will work seamlessly with the still emerging OGC APIs and other services, such as the metadata, via API-Records and API-Processes. We know it is very compatible with API-Features. Hope that makes sense. Chris

**Comment by turingtestfail** [comment]
I will be working on updating the GeoTools CQL-JSON module (and by extension GeoServer) from last summer (https://github.com/geotools/geotools/tree/main/modules/unsupported/cql-json)  to be current with the CQL2 JSON spec located at https://github.com/opengeospatial/ogcapi-features/tree/master/cql2/standard/schema/examples

**Comment by IvanSanchez** [comment]
I'm working on a javascript library for map display called Gleo (https://gitlab.com/IvanSanchez/gleo); it overlaps leaflet/openlayers use cases.

Currently there's a basic WMS client implementation.

The focus is to see how the Maps OGC API compares to WMS, and try code a basic client implementation. I plan to also have a look at the Features and Tiles APIs.

**Comment by pixalytics** [comment]
I'll be working on a backend implementation, for generating catalogs, developed as part of Testbed-17 - see https://github.com/opengeospatial/T17-API-D168 

Other partners in the Testbed-17 activity developed servers and clients, and the Engineering Report is available here http://ogc.pages.ogc.org/T17-D040-API-Experiments-ER/documents/document.html

**Comment by doublebyte1** [comment]
I am going to be working on pygeoapi, mostly on testing the elasticsearch data provider and the implementation of OAR.

**Comment by mmacata** [comment]
We will enhance the [geoserver-grass-raster-datastore](https://github.com/mundialis/geoserver-grass-raster-datastore) - making a test deployment, fixing bugs, enhance documentation and also publish and test GRASS GIS addons to publish a raster layer with style.
