### ISSUE TITLE
What GitHub/Gitlab Issues has the 2023 Open Standards & Open Source Code Sprint created in other repositories?

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/developer-events#46]
Please let us know what GitHub/Gitlab Issues you have created during the code sprint.

**Comment by IvanSanchez** [comment]
Not an issue, but a small repo: https://gitlab.com/IvanSanchez/homeassistant-sensorthings

That contains a (minimally working) OGC SensorThings client, implemented as a HomeAssistant integration.

**Comment by ghobona** [comment]
https://github.com/opengeospatial/ogcapi-org/issues/33

**Comment by cportele** [comment]
Discussion on schemas in OGC API Features: https://github.com/opengeospatial/ogcapi-features/issues/740#issuecomment-1523806821

**Comment by doublebyte1** [comment]
I have mentioned them in this issue: https://github.com/opengeospatial/developer-events/issues/47#issue-1689470840

**Comment by ghobona** [comment]
https://github.com/opengeospatial/ogcapi-common/issues/329

**Comment by ghobona** [comment]
https://github.com/opengeospatial/ogcapi-common/issues/330

**Comment by ghobona** [comment]
https://github.com/apache/incubator-baremaps/issues/632

**Comment by ghobona** [comment]
https://github.com/apache/incubator-baremaps/issues/634

**Comment by ghobona** [comment]
On 2024https://github.com/opengeospatial/ogcapi-records/issues/254

**Comment by ghobona** [comment]
https://github.com/opengeospatial/ogcapi-records/issues/255

**Comment by ghobona** [comment]
https://github.com/opengeospatial/ogcapi-records/issues/256

**Comment by ghobona** [comment]
https://github.com/geoserver/geoserver/pull/6801

**Comment by ghobona** [comment]
https://github.com/geoserver/geoserver/pull/6802

**Comment by ghobona** [comment]
https://github.com/opengeospatial/teamengine/issues/575

**Comment by ghobona** [comment]
https://github.com/opengeospatial/teamengine/issues/574

**Comment by ghobona** [comment]
https://github.com/opengeospatial/teamengine/issues/577

**Comment by ghobona** [comment]
https://github.com/opengeospatial/teamengine/issues/578

**Comment by ghobona** [comment]
https://github.com/opengeospatial/teamengine/issues/579
