### ISSUE TITLE
What GitHub/Gitlab Issues has the Tiling Interfaces Code Sprint created in other repositories?

### ISSUE THREAD

**Issue by doublebyte1** [opengeospatial/developer-events#68]
Please let us know what GitHub/Gitlab Issues you have created during the code sprint. :-)

**Comment by pixalytics** [comment]
Updating the GDAL drivers links for the OGCAPI in the documentation: https://github.com/OSGeo/gdal/issues/7936

**Comment by jerstlouis** [comment]
GeoData Tilesets: Clarify whether tilesets-* links should be included in /collections: https://github.com/opengeospatial/ogcapi-tiles/issues/156
Issues using ogr2ogr with OGC API vector tiles: https://github.com/OSGeo/gdal/issues/7934
OGC API - Tiles issues in pygeoapi: https://github.com/geopython/pygeoapi/issues/1262

**Comment by m-mohr** [comment]
Discoverability of Tiles resources: https://github.com/opengeospatial/ogcapi-tiles/issues/157

**Comment by jerstlouis** [comment]
@doublebyte1 Did you end up filing a QGIS issue for not being able to select one of those zoom levels with OGC API - (vector) Tiles ?

**Comment by doublebyte1** [comment]
> @doublebyte1 Did you end up filing a QGIS issue for not being able to select one of those zoom levels with OGC API - (vector) Tiles ?

Not yet. I would like to solve the issue on GDAL side, first: https://github.com/OSGeo/gdal/issues/7969
