### ISSUE TITLE
What is everybody going to be working on at the Open Standards Sprint?

### ISSUE THREAD

**Issue by doublebyte1** [opengeospatial/developer-events#71]
Post a comment letting us know what you are going to be working on :-)

**Comment by joanma747** [comment]
We would like to propose a STAplus use case that allows for restricted data sharing based on a business contract. The storyline of the use cases goes as follows:

> A bus company in Milan has a new set of electric buses to operate and partially replace diesel buses. The DPD courier company has a fleet of vans that mount air quality sensors. This data is stored in a STAplus (Party=DPD) as non-validated. Anonymous users can only get access to validated data released with some delay. In the AirQuality data space the bus company contracts the DPD to share the data in real time with the bus company in exchange for money. This data is used to create operational routes for electric buses in the areas that are more polluted. The bus company can use other sources of AirQuality "for free" as citizen science data according to the licences (without any contract). This use case contemplates the needs of the EU Horizon Europe CitiObs and AD4GD

This is a diagram of the use case

![image](https://github.com/opengeospatial/developer-events/assets/5230444/46676a98-d852-4911-9cd6-d23676850124)

**Comment by tomkralidis** [comment]
- OGC API - Records
  - specification completion / ATS
  - federation extension
- pygeoapi
  - OGC API - Records support completion / ATS
  - OGC API - Processes CITE Compliance
- pycsw
   - OGC API - Records support completion / ATS
   - federation (in conjunction with OGC API - Records discussion)

**Comment by jerstlouis** [comment]
The main thing I plan to focus on at this code sprint is to advance the [specification documents](https://github.com/opengeospatial/CDBV2-2023-Summer-Workshop/wiki/Summer-2023-CDB-Workshop#documents) for OGC CDB 2.0 GeoPackage data store and the related GeoPackage extensions as a follow-up to [our summer workshop](https://github.com/opengeospatial/CDBV2-2023-Summer-Workshop/wiki/Summer-2023-CDB-Workshop) on practical interoperability experiments.

In parallel to this, [OGC API - Maps](https://docs.ogc.org/DRAFTS/20-058.html), [OGC API - Coverages](https://docs.ogc.org/DRAFTS/19-087.html) and [OGC API - DGGS](https://opengeospatial.github.io/ogcna-auto-review/21-038.html) should be getting close to ready for OAB Review / RFC period, so I will be looking forward to sharing updates on this, resolving issues in the spec, and support implementations and Technology Integration Experiments with our implementations.

We are also making progress on [Styles & Symbology](https://opengeospatial.github.io/ogcna-auto-review/18-067r4.html), and will also be happy to provide an update and encourage initial implementations.

**Comment by doublebyte1** [comment]
> * OGC API - Records
>   
>   * specification completion / ATS
>   * federation extension
> * pygeoapi
>   
>   * OGC API - Records support completion / ATS
>   * OGC API - Processes CITE Compliance
> * pycsw
>   
>   * OGC API - Records support completion / ATS
>   * federation (in conjunction with OGC API - Records discussion)

@tomkralidis does the record support work on pygeoapi include the CSW bridge? :)

**Comment by tomkralidis** [comment]
@doublebyte1 yup! Added to the list of goals 😀

**Comment by deanhintz** [comment]
We - Trent Kading, Dave Campanas and I - are going to be working on writing MUDDI GML and CityGML3 with Safe Software's FME data integration platform. Clemens & Johannes from Interactive Instruments generated a GML app schema last week based on the MUDDI logical model and some geometry interpretations we discussed. I put together a basic demo in FME which creates dummy data and writes it to MUDDI GML using the standard GML writer. We then plan on writing data from Burnaby to MUDDI GML using the same approach. Trent and I are working on MUDDI writing.

Dave C is working on CityGML2 to CityGML3 writing and IFC to CityGML3.

**Comment by ghobona** [comment]
Thanks everyone!
