### ISSUE TITLE
Who is going to present a demo of their work during the Final Demonstration session?

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/developer-events#90]
Please let us know by 14:00 UTC if you are planning to present your demo during the final session.

Post your name to this issue.

**Comment by tomkralidis** [comment]
@tomkralidis

**Comment by cportele** [comment]
Clemens Portele (@cportele)

**Comment by ricardogsilva** [comment]
Ricardo Garcia Silva

**Comment by lvdbrink** [comment]
Linda van den Brink / Arnoud de Boer / Joost Farla
Before 16:00 UTC please, because we have to leave early to catch our train.

**Comment by bradh** [comment]
@bradh

**Comment by deanhintz** [comment]
@deanhintz

**Comment by sumitsane** [comment]
Sumit Sen

**Comment by securedimensions** [comment]
Andreas Matheus & Joan Maso

**Comment by cartogreaves** [comment]
Rebecca Aspin & Richard Hargreaves
Simple MUDDI Logical Schema

**Comment by cdharbin** [comment]
Charla Harbin, OGC API Records demo

**Comment by IvanSanchez** [comment]
Me! Me! @IvanSanchez 

I'll need https://ivansanchez.gitlab.io/geo-heif-viewer/map.html and some of https://github.com/opengeospatial/developer-events/tree/master/2023/Open-Standards-Code-Sprint/publicly-releasable-sample-data/bradh

**Comment by joanma747** [comment]
Map Browser using a OGC API maps server serving heif files (internally in jpeg2000).
